### ISSUE TITLE
[BUG] - Error onKeyDown in console bij gebruik van datepicker

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-datepicker#118]
**Omschrijf het probleem**
In project IBO (inspraak) viel het me op dat er veel console errors gelogged werden. Soms is er al 1 log bij het openen van de pagina, maar het probleem stelt zich vooral voor wanneer je eender welke toets op je keyboard indrukt. 

**Hoe te reproduceren**
Ga bijvoorbeeld naar https://inspraak-ontwikkel.omgeving.vlaanderen.be/ 
Open de console 
Druk op eender welke toets op je keyboard.

**Gewenst gedrag**
Geen error logs

**Screenshots**
<img width="1679" alt="Screenshot 2020-07-07 at 14 37 42" src="https://user-images.githubusercontent.com/8820456/86783982-43cb9e80-c061-11ea-96c8-92471c840ae4.png">

**Omgeving (gelieve aan te vullen):**
 - Browser Chrome
 - Versie Version 83.0.4103.116 (Official Build) (64-bit)
 - Versie component 3.0.5

**Comment by coemans** [comment]
@Rubenth ik kan het probleem lokaal niet meer reproduceren. Doet het probleem zich nog voor in IBO bij gebruik van v3.2.0 of de #master branch?

**Comment by Rubenth** [comment]
@coemans net op iBO getest (datepicker v3.2.0) en het probleem doet zich inderdaad niet meer voor. Dit kan dus afgesloten worden.
