### ISSUE TITLE
[BUG] - Datepicker met visual-format heeft andere styling als datepicker zonder visual-format

### ISSUE THREAD

**Issue by FreekRombauts** [milieuinfo/webcomponent-vl-ui-datepicker#121]
**Omschrijf het probleem**
Datepicker met visual-format heeft andere styling als datepicker zonder visual-format

**Hoe te reproduceren**
Zet twee datepickers naast elkaar, 1 met en 1 zonder visual format. Die met visual-format ziet er anders uit als die zonder.

```
                <vl-datepicker
                   format="Y-m-d"
                   id="periodeEindigtNa"
                   name="periodeEindigtNa"></vl-datepicker>
                <vl-datepicker
                   format="Y-m-d"
                   visual-format="d-m-Y"
                   id="periodeBegintVoor"
                   name="periodeBegintVoor"></vl-datepicker>
```

**Gewenst gedrag**
Zelfde styling voor datepicker, ongeacht of er een visual-format is of niet.

**Screenshots**

In chrome (onderste is met visual-format):

<img width="361" alt="image" src="https://user-images.githubusercontent.com/58428396/88898273-c56fb000-d24c-11ea-907b-ae2846427788.png">

In safari (onderste is met visual-format):

<img width="366" alt="image" src="https://user-images.githubusercontent.com/58428396/88898645-5050aa80-d24d-11ea-8776-a68624254b50.png">

**Omgeving (gelieve aan te vullen):**
 - Browser: Chrome & Safari [vb. chrome, safari]
 - Versie component: 3.0.5

**Extra info**
Potentieel zelfde oorzaak als https://github.com/milieuinfo/webcomponent-vl-ui-datepicker/issues/76

**Comment by FreekRombauts** [comment]
@coemans , ik heb hertest met die pull request, maar krijg nog steeds exact dezelfde layout problemen.

**Comment by coemans** [comment]
@FreekRombauts kan je in de node_modules controleren of de wijzigingen correct binnengetrokken werden in de applicatie?

**Comment by coemans** [comment]
@FreekRombauts ondertussen heb ik het probleem applicatief kunnen reproduceren en oplossen. Je mag dit altijd nog eens verifiëren via de #visual-format-style branch.

**Comment by FreekRombauts** [comment]
@coemans , nagekeken en lijkt in orde te zijn.
