### ISSUE TITLE
[BUG] - Datepicker vl-data-error heeft geen effect

### ISSUE THREAD

**Issue by pharacyde** [milieuinfo/webcomponent-vl-ui-datepicker#131]
**Omschrijf het probleem**
demo van "Datepicker error" toont geen error (safari)
cfr https://webcomponenten.omgeving.vlaanderen.be/demo/vl-datepicker.html

**Gewenst gedrag**
Datepicker zou rood moeten worden.

**Comment by coemans** [comment]
@pharacyde was dit alleen een probleem op de demo pagina en niet applicatief? Vermoedelijk had de vorige demo pagina nog een oude vl-ui-datepicker versie, bij de huidige demo pagina kan ik het probleem niet reproduceren.

**Comment by pharacyde** [comment]
@coemans  klopt puur demo pagina issue. Applicatief in IBO bvb, komt het omdat we visual format gebruiken, maar daar is al een ander ticket van.

**Comment by coemans** [comment]
Aangezien het niet meer reproduceerbaar is op de demo pagina en er voor jullie applicatief probleem een ander issue bestaat, zal ik dit ticket afsluiten.
