### ISSUE TITLE
[BUG] - Focus call heeft geen effect

### ISSUE THREAD

**Issue by pharacyde** [milieuinfo/webcomponent-vl-ui-datepicker#132]
**Omschrijf het probleem**
focus() call op de component heeft geen effect.

**Hoe te reproduceren**
target de component via chrome dev tools bvb en roep $0.focus() op.

**Comment by FreekRombauts** [comment]
@coemans , getest. Focus call werkt nu bij gewone datepicker, maar nog steeds niet bij datepicker met visual-format.

**Comment by coemans** [comment]
@FreekRombauts inderdaad, dat zou nu opgelost moeten zijn.

**Comment by FreekRombauts** [comment]
@coemans , inderdaad opgelost nu.
