### ISSUE TITLE
[BUG] - dubbel icoon bij responsive window Chrome

### ISSUE THREAD

**Issue by SBylemans** [milieuinfo/webcomponent-vl-ui-datepicker#140]
**Omschrijf het probleem**
Bij het openen van de demo pagina in responsive mode (responsive mode moet aanstaan bij openen, indien 2de icoon niet zichtbaar -> refresh) zal er in de datepicker 2 iconen te zien zijn.

**Hoe te reproduceren**
Open demo pagina in responsive mode of refresh in responsive mode.

**Gewenst gedrag**
Geen 2 iconen

**Screenshots**
![image](https://user-images.githubusercontent.com/5698858/97591374-d7095500-19ff-11eb-8a0f-daadc7579aca.png)

Ook aanwezig bij AIV

**Comment by coemans** [comment]
Dit blijkt op mobiele toestellen geen probleem te zijn, vermoedelijk dus een probleem in combinatie met responsieve mode maar lijkt mij echt niet de moeite om hier enige vorm van investering te doen.
