### ISSUE TITLE
[FEATURE] - ready functie die aangeeft wanneer datepicker volledig geïnitialiseerd is

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-datepicker#145]
**Wat moet er gebeuren**
Het zou praktisch zijn dat de datepicker een publieke _ready_ functie heeft zoals sommige andere componenten. Bij een upgrade (van versie 1.1.0 naar 3.2.2) bleken de unit testen van onze componenten die een datepicker gebruiken, gebroken. Het probleem was een timing issue waarbij de _dress_ van de datepicker nog niet afgerond was.

Als workaround werd er een wait toegevoegd (cfr datepicker unit tests): `await awaitUntil(() => this._datepicker._dressed);`

**Extra info**
Indien dit probleem kan opgelost worden zonder _ready_ functie, maar pas een _define_ te doen wanneer de datepicker klaar is, des te beter.

**Comment by kevcraey** [comment]
https://www.milieuinfo.be/jira/browse/UIG-2192
