### ISSUE TITLE
[BUG] - kleur van disabled datums is anders bij vorige / volgende maand

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-datepicker#147]
**Omschrijf het probleem**
In de laatste versie op demo pagina merk ik dat de vorige/volgende maand niet volledig gedisabled meer lijkt. Het is een zachter grijs, maar donkerder dan de disabled kleur.

**Gewenst gedrag**
Disabled datums overal dezelfde kleur, ongeacht de maand

**Screenshots**
![image](https://user-images.githubusercontent.com/29454303/104882226-feb6ec00-5962-11eb-8918-e4de9df7d0e1.png)

**Omgeving:**
 - Browser any
 - Versie component 3.2.3

**Extra info**
Zie ook https://www.milieuinfo.be/jira/browse/UIG-816

**Comment by kevcraey** [comment]
ticket aangemaakt https://www.milieuinfo.be/jira/browse/UIG-2191
