### ISSUE TITLE
Datepicker gaat niet meer open naar links

### ISSUE THREAD

**Issue by MayaVC** [milieuinfo/webcomponent-vl-ui-datepicker#149]
**Omschrijf het probleem**
In versie 3.2.3 gaat de datepicker binnen Promon open naar links, zoals gewenst. In versie 3.2.4 gaat die open naar rechts, waardoor je in de side-sheet moet scrollen. 

**Gewenst gedrag**
Datepicker kalender gaat open naar links.

**Screenshots**
Versie 3.2.4
![Schermafbeelding 2021-01-27 om 19 09 14](https://user-images.githubusercontent.com/31885631/106034529-4f50e680-60d3-11eb-8956-fa3ed1744937.png)
![Schermafbeelding 2021-01-27 om 19 09 43](https://user-images.githubusercontent.com/31885631/106034546-52e46d80-60d3-11eb-91c2-12413b928a41.png)

Versie 3.2.3 (gewenst gedrag):
![Schermafbeelding 2021-01-27 om 19 13 53](https://user-images.githubusercontent.com/31885631/106034960-d7cf8700-60d3-11eb-8ded-a827daabb2b0.png)

**Omgeving (gelieve aan te vullen):**
 - Chrome
 - Versie [vb. 22]
 - 3.2.4

**Extra info**

**Comment by pharacyde** [comment]
Ter info, als we volgende code toepassen dan komt de datepicker op de juiste plaats te staan

```
  // cfr datepicker.js code:
  //    configPos = self.config.position.split(" "),
  //    configPosVertical = configPos[0],
  //    configPosHorizontal = configPos.length > 1 ? configPos[1] : null,
  // configPosHorizontal moet right zijn, anders wordt de positie slecht berekend.
  awaitUntil(() => datepicker._dressed)
      .then(() => {
        datepicker._flatpickr.config.position = 'auto right';
      });
```

Komt erop neer dat we de config van flatpicker op 'auto right' zetten. En dan komt die links te staan :-)

**Comment by kevcraey** [comment]
ticket aangemaakt
