### ISSUE TITLE
[BUG] - change event propageert niet

### ISSUE THREAD

**Issue by SBylemans** [milieuinfo/webcomponent-vl-ui-datepicker#150]
**Omschrijf het probleem**
Wanneer we de input van de datepicker leegmaken dmv de backspace, dan wordt er geen change event getriggered.

**Gewenst gedrag**
Wel een change event laten propageren
Zie branch change-event-propagation.

**Comment by coemans** [comment]
Probleem is niet reproduceerbaar bij versie 3.2.4, in samenspraak beslist om issue en PR te sluiten zonder gevolg.
