### ISSUE TITLE
[BUG] - de datepicker lijkt andere inputs op dezelfde pagina te breken

### ISSUE THREAD

**Issue by SanderKleykens** [milieuinfo/webcomponent-vl-ui-datepicker#166]
**Omschrijf het probleem**
Van zodra er een `<vl-datepicker>` geintroduceerd wordt op een pagina, lijkt de `vl-pattern` feature (en mogelijks nog andere features) van `<vl-input-field>` elementen kapot te gaan.

**Hoe te reproduceren**
```
<vl-demo data-vl-title="Kaput">
    <vl-datepicker></vl-datepicker>
    <input is="vl-input-field" data-vl-pattern="numerical" data-vl-validation-type="numerical"/>

    <div>Haal de vl-datepicker weg en de pattern van de vl-input-field doet zijn werk weer zoals verwacht :)</div>
</vl-demo>
```

Zie ook de demo pagina van https://github.com/milieuinfo/webcomponent-vl-ui-datepicker/tree/reproduce-datepicker-input-combination-bug

**Gewenst gedrag**
Dat de vl-input-field's gewoon blijven werken zoals verwacht.

**Comment by kevcraey** [comment]
ticket aangemaakt
