### ISSUE TITLE
[BUG] - Validatie werkt enkel na enter, niet na tab

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-datepicker#22]
**Omschrijf het probleem**
Indien men tabt gebeurd er geen validatie, en lijkt me ook de data niet opgeslagen.

Wanneer men data input en entert, wordt de datepicker ook gesynchroniseerd, wat niet bij tab is...

**Comment by coemans** [comment]
Datepicker heeft geen validatie, dus voorlopig afgesloten.
