### ISSUE TITLE
[BUG] - Popup verschijnt, al dan niet, willekeurig op scherm

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-datepicker#23]
**Omschrijf het probleem**
popup verschijnt, al dan niet, willekeurig op scherm

**Screenshots**
<img width="1378" alt="UIG-195_20190807" src="https://user-images.githubusercontent.com/1628243/64429723-f3895600-d0b6-11e9-9a82-f9107d8f7b5e.png">
<img width="1369" alt="UIG-195_20190807_2" src="https://user-images.githubusercontent.com/1628243/64429725-f5531980-d0b6-11e9-8536-ade2b338e649.png">
<img width="1371" alt="UIG-195_20190807_1" src="https://user-images.githubusercontent.com/1628243/64429732-f7b57380-d0b6-11e9-94fe-23a26a8ca27c.png">

**Omgeving (gelieve aan te vullen):**
 - Browser Firefox

**Comment by coemans** [comment]
Niet reproduceerbaar na refactoring, release versie 1.0.0.
