### ISSUE TITLE
[BUG] - Atribuut human-friendly: manuele ingave wordt herberekend

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-datepicker#24]
**Omschrijf het probleem**
Manuele ingave wordt herberekend waardoor je soms de verkeerde datum krijgt, waar het soms beter is om een validatie fout te gooien.

vb:

dinsdag 4 december 2012

--> JULI ipv december

--> zondag 4 december 2011

**Comment by coemans** [comment]
In combinatie met vl-ui-pattern doet dit probleem zich niet voor en worden ongeldige datums live aangepast.
