### ISSUE TITLE
[BUG] - Date range waarde is tekstueel verwarrend

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-datepicker#25]
**Omschrijf het probleem**
Wanneer je een range van meer als 1 datum kiest, is het wenselijk om "tot en met" te gebruiken ipv "tot". Zo is de laatste dag inclusief zoals je aangeduid hebt op de kalender.

vb:

    selecteer 1,2,3,4,5 augustus 2019
    geeft als resultaat "1 augustus 2019 tot 5 augustus 2019"

gewenst resultaat: "1 augustus 2019 tot en met 5 augustus 2019"

**Comment by coemans** [comment]
De implementatie is identiek aan die van Webuniversum, maar ik zal informeren naar de mening van Webuniversum hierover.

**Comment by coemans** [comment]
Gemeld aan Webuniversum en ze zijn akkoord met de opmerking, wordt door hen opgepikt en automatisch gefixt bij ons bij een volgende update.
