### ISSUE TITLE
[BUG] - multiple-date-picker - selectie wordt niet gesorteerd

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-datepicker#26]
**Omschrijf het probleem**
Nu wordt de selectie getoond in volgorde van aanvinken.

Properder zou zijn dat deze op datum gesorteerd zijn...

**Comment by coemans** [comment]
Voorlopig geen ondersteuning voor multiple datepicker gezien dit bij Webuniversum ook (nog) niet aangeboden wordt. Pas wanneer er nood aan is, volgt een implementatie.

Los van het feit dat de feature niet meer voorzien is, lijkt me de volgorde van input door de gebruiker correct. Het lijkt me niet correct om dit live te gaan sorteren, want dan is het niet meer de input zoals de gebruiker het opgegeven heeft. Nadien bij het verwerken kunnen de datums uiteraard wel gesorteerd worden.
