### ISSUE TITLE
[BUG] - Date range met niet-beschikbare datums - kalender verspringt op scherm

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-datepicker#27]
**Omschrijf het probleem**
kalender verspringt naar onderaan scherm

**Hoe te reproduceren**
1. selecteer 1 dag
2. open de datepicker terug
3. selecteer een nieuwe datum

kalender verspringt naar onderaan scherm

**Omgeving (gelieve aan te vullen):**
 - Browser Chrome, Safari

**Comment by coemans** [comment]
Niet reproduceerbaar na refactoring, release versie 1.0.0.
