### ISSUE TITLE
[BUG] - Timepicker - kleine pijltjes onder grote pijlen

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-datepicker#28]
**Omschrijf het probleem**
Wanneer je met de pijltjes het uur zou wijzigingen zie je op de achtergrond van de pijlen, kleine pijltjes.

Dit is ook op webuniversum.

 

 
<img width="1255" alt="UIG-200_20190807" src="https://user-images.githubusercontent.com/1628243/64429979-8de99980-d0b7-11e9-8090-72dbea0c0933.png">

**Comment by coemans** [comment]
In bepaalde browsers (zoals Chrome) worden bij input velden van type number de arrows getoond om aan de gebruiker duidelijk te maken dat hij met behulp van de pijltjes de input waarde kan verhogen of verlagen. Het is mogelijk dit met CSS te verbergen.

Gezien dit zich ook voordoet bij de component van Webuniversum, zal ik het daar melden.

**Comment by coemans** [comment]
Gemeld aan Webuniversum en ze zijn akkoord met de opmerking, wordt door hen opgepikt en automatisch gefixt bij ons bij een volgende update.

**Comment by coemans** [comment]
Probleem is niet meer reproduceerbaar, dus zal vermoedelijk reeds opgelost zijn met een update.
