### ISSUE TITLE
[BUG] - Enter zet niet de waarde in de datepicker bij een manuele ingave

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-datepicker#29]
**Omschrijf het probleem**
Wanneer we manueel een waarde ingeven in het input veld, wordt het niet opgeslagen nadat de gebruiker op "enter" duwt. Deze functionaliteit is wel voorzien bij Webuniversum.

**Comment by coemans** [comment]
Probleem werd opgelost zonder unit test gezien de fix gebeurd is in de Webuniversum code. Later zal er wel een e2e test toegevoegd worden om deze bug te coveren.
