### ISSUE TITLE
[BUG] - Date-timepicker - niet mogelijk om uur te selecteren want kalender sluit na datum keuze

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-datepicker#30]
**Omschrijf het probleem**
niet mogelijk om uur te selecteren want kalender sluit na datum keuze

**Hoe te reproduceren**
1. selecteer datum
2. kalender sluit en slaagt datum op met uur "12:00"
3. indien men dan de kalender terug opent is het mogelijk een uur te selecteren

**Gewenst gedrag**
Gewenst resultaat (zie webuniversum):

Kies datum, dan komt onderaan de datepicker de mogelijkheid om uur te selecteren.Licht kort en duidelijk toe wat het gewenst gedragd is.

**Comment by coemans** [comment]
Niet reproduceerbaar na refactoring, release versie 1.0.0.
