### ISSUE TITLE
[BUG] - Manuele input werkt niet

### ISSUE THREAD

**Issue by ZhaodiFengVlaanderen** [milieuinfo/webcomponent-vl-ui-datepicker#53]
**Omschrijf het probleem**
De calendar verandert niet na een manuel input.

**Comment by coemans** [comment]
Duplicatie van #29 of is het een ander probleem?

**Comment by ZhaodiFengVlaanderen** [comment]
> Duplicatie van #29 of is het een ander probleem?

De date input werkt ook niet. De kalender verandert niet als ik manual een date intypen.

**Comment by driesva** [comment]
@coemans 
Het gevolg is ook dat wanneer je een datum invult en deze daarna verwijdert, de originele datum in de onderliggende kalender (flatpickr) blijft zitten. Dit lijkt ook zo bij web universum te zijn.
Op het eerste zicht is er geen manier op de gekozen datum te verwijderen:
- zoals gemeld in dit ticket wijzigt de kalender niet na manueel verwijderen
- er is nergens een kruisje in de text input om de waarde te verwijderen
- de-selecteren in de kalender gaat ook niet

**Comment by driesva** [comment]
Blijkbaar is het bij web universum wel mogelijk als je de waarde manueel wegdoet en daarna op enter duwt. Maar bij onze web componenten werkt dit niet, zie #29 
Maar niet gebruiksvriendelijk dat je van een gebruiker verwacht enter te typen...

**Comment by coemans** [comment]
Manuele input (met enter) is nu wel mogelijk, cfr. #29. @driesva ik zal melden bij Webuniversum dat bij een tab de datepicker niet aangepast wordt. Voor het tab probleem heb ik een nieuw issue aangemaakt: #65. Dit issue is dan eigenlijk een duplicate van #29 en kan bijgevolg ook gesloten worden.
