### ISSUE TITLE
[BUG] Geen validatie op formaat

### ISSUE THREAD

**Issue by blens-test** [milieuinfo/webcomponent-vl-ui-datepicker#54]
**Omschrijf het probleem**
Er is geen validatie op formaat

**Hoe te reproduceren**
Geef een jaartal van 5 cijfers. 

**Gewenst gedrag**
Webuniversum kapt deze af naar 4 cijfers.
Maar eigenlijk wil je een validatie fout zien die zegt dat het formaat niet klopt.

**Comment by ZhaodiFengVlaanderen** [comment]
U kunt zelfs free-text intypen.

**Comment by coemans** [comment]
Hiervoor kan de [vl-ui-pattern](https://github.com/milieuinfo/webcomponent-vl-ui-pattern) gebruikt worden.

**Comment by driesva** [comment]
Niet getest, maar bedoel je dat dit mogelijk is `<vl-datepicker data-vl-pattern="date"`... ?

**Comment by coemans** [comment]
Dat zou inderdaad mogelijk moeten zijn, maar het zou kunnen dat momenteel het attribuut nog niet goed gedelegeerd wordt. Ik zal dit nakijken en uitbreiden indien nodig.
