### ISSUE TITLE
[BUG] - Datums buiten min/max date staat nog altijd in zwart. 

### ISSUE THREAD

**Issue by ZhaodiFengVlaanderen** [milieuinfo/webcomponent-vl-ui-datepicker#56]
**Omschrijf het probleem**
Datums buiten min/max date staat nog altijd in zwaarte(well niet klikbare).

**Comment by driesva** [comment]
@ZhaodiFengVlaanderen  heb jij hier een screenshot van?

**Comment by ZhaodiFengVlaanderen** [comment]
![Sep-17-2020 12-45-30](https://user-images.githubusercontent.com/51441000/93460593-bd92ca80-f8e3-11ea-88a7-07d4a78af4c8.gif)

- Ik kan dit reproduceren door de code van VHRMVC te manipuleren

- VHRMVC is nog met een zeer oude versie (1.10)

**Comment by coemans** [comment]
Probleem lijkt zich niet meer voor te doen in de huidige versie. Ik zie niet meteen een release waar dit rechtstreeks in opgelost werd, dus vermoedelijk opgelost door een huisstijl update.

<img width="2560" alt="screenshot" src="https://user-images.githubusercontent.com/11139249/93489081-61da3880-f907-11ea-8001-9cd5e7579926.png">
