### ISSUE TITLE
[FEATURE] - Introduceren value getter en setter

### ISSUE THREAD

**Issue by ZhaodiFengVlaanderen** [milieuinfo/webcomponent-vl-ui-datepicker#57]
**Wat moet er gebeuren**
Getter en Setter van geselecteerd datum.

**Comment by pharacyde** [comment]
In DSI zien we ook dat de selected-date attribuut niet altijd even goed werkt wanneer een custom formattering gebruikt wordt.

We zijn dan verplicht om de waarde van een vl-ui-datepicker op volgende manier te binden

```
   this._input()._flatpickr.setDate(this.value, true);
  
  _input() {
    return this._component().shadowRoot.querySelector('#input');
  }
```
