### ISSUE TITLE
[BUG] - Rendering z-index probleem in combinatie met vl-input-group

### ISSUE THREAD

**Issue by coemans** [milieuinfo/webcomponent-vl-ui-datepicker#58]
**Omschrijf het probleem**
In combinatie met de vl-input-group is er een z-index rendering probleem wanneer meerdere vl-datepicker webcomponenten onder elkaar gerenderd worden. De vl-button-input-addon is dan zichtbaar boven de datepicker.

**Hoe te reproduceren**
Probleem is te reproduceren op de demo pagina.

**Gewenst gedrag**
De vl-button-input-addon moet onder de datepicker gerenderd worden.

**Screenshots**
<img width="2558" alt="Screenshot 2019-11-14 at 17 45 57" src="https://user-images.githubusercontent.com/11139249/68877763-e320d780-0706-11ea-9588-480c84d1e355.png">

**Omgeving (gelieve aan te vullen):**
 - Versie component **1.0.4**

**Comment by coemans** [comment]
Probleem stelt zich ook in DSI aangezien daar meerdere datums ingegeven moeten worden, @pharacyde ter info.

**Comment by pharacyde** [comment]
+1
