### ISSUE TITLE
[FEATURE] - Change event propageren

### ISSUE THREAD

**Issue by pharacyde** [milieuinfo/webcomponent-vl-ui-datepicker#59]
**Wat moet er gebeuren**
vl-ui-datepicker zou een change event moeten uitsturen wanneer een datum / tijd geselected wordt. 

Nu zijn we verplicht om op de interne input een listener toe te voegen.
```
  this._input().addEventListener('change', (e) => this._changeValue(e));
  _input() {
    return this._component().shadowRoot.querySelector('#input');
  }
```

#input is de id van het input veld waar flatpicker op gebind is.

Het volgende zou mogelijk moeten zijn

```
      <vl-datepicker
         format="d-m-Y"
         id="localdate"
         name="localdate"
         @change="${this._changeValue}"
         disable-input
      ></vl-datepicker>
```

**Comment by driesva** [comment]
Aangezien we dit nodig hebben voor vl-ui-rich-table heb ik deze functionaliteit toegevoegd

**Comment by coemans** [comment]
De bijhorende PR #60 is bijna een jaar oud en voegt niet alleen het change event toe maar ook een value getter die een breaking change introduceert. Ik heb daarom een nieuwe PR gemaakt. Er wordt nu een change event verstuurd. De value kan opgevraagd worden via `event.target.value`.

Indien het ook nog gewenst is om de value getter aan te passen van de waarde van het input veld naar een JSON object, een Date object of een array van Date objects, kan er best een nieuw issue aangemaakt worden zodat dit verder besproken/geïmplementeerd kan worden.

**Comment by FreekRombauts** [comment]
@coemans , even getest en werkt alleen volledig bij datepickers zonder visual format.

Bij datepickers met visual format zijn er alleen change events indien een andere datum gekozen wordt via het calender ding. Indien je manueel een andere datum intypt in de tekstfield dan is er geen change event.

**Comment by coemans** [comment]
@FreekRombauts inderdaad, probleem werd ondertussen opgelost.

**Comment by FreekRombauts** [comment]
@coemans , heb nog eens opnieuw getest en lijkt nog steeds niet te werken

**Comment by coemans** [comment]
Offline gesynchroniseerd met @FreekRombauts en blijkbaar werd de nieuwe waarde niet bevestigd met de enter toets. Er bestaat al een issue op bij tab/blur ook een change te triggeren: #65. Huidig issue op zich is opgelost, om de scope klein te houden stel ik voor dat we hier een merge uitvoeren en #65 uitvoeren.
