### ISSUE TITLE
[BUG] - Tab/blur update de manuele input niet bij de datepicker

### ISSUE THREAD

**Issue by coemans** [milieuinfo/webcomponent-vl-ui-datepicker#65]
**Omschrijf het probleem**
Wanneer een gebruiker de waarde wijzigt via het input veld, wordt de waarde niet aangepast in de datepicker. Dit probleem stelt zich ook bij Webuniversum.

**Hoe te reproduceren**
Op de demo pagina de waarde wijzigen via het input veld en vervolgens de datepicker openen.

**Gewenst gedrag**
Bij een tab moet de datepicker de manuele wijzigingen verwerken.

**Omgeving (gelieve aan te vullen):**
 - Versie component **1.0.4**

**Comment by FreekRombauts** [comment]
@coemans , om de omschrijving een beetje aan te vullen, ik kan aan volgende cases denken:
* tab
* shift-tab
* enter (al in orde)
* klikken buiten de input

Mogelijk zijn er nog andere maar dit zijn denk ik wel de belangrijkste. uiteraard alleen een change event bij deze blurs indien er effectief een change is aan de input.

**Comment by coemans** [comment]
PR #877 aangemaakt bij AIV met change event uitbreiding.

**Comment by coemans** [comment]
@FreekRombauts indien PR goedgekeurd wordt, zal bij de volgende huisstijl upgrade dit issue opgelost en gesloten worden. Als jullie de feature vroeger nodig hebben, kan de code op ons niveau vervroegd toegepast worden. Graag dan een seintje.
