### ISSUE TITLE
[BUG] - Error wordt niet correct getoond in combinatie met visual-format property

### ISSUE THREAD

**Issue by pharacyde** [milieuinfo/webcomponent-vl-ui-datepicker#76]
**Omschrijf het probleem**
Gegeven

`  <vl-datepicker
         visual-format="d-m-Y"
         format="Y-m-d"
         id="localdate"
         name="localdate"
         disable-input>
  </vl-datepicker>
`

Wanneer we hier het attribuut error op willen zetten, wordt de input niet rood. Een eerste onderzoek wijst dat het gebruik van de property visual-format werkt met twee input velden. Waarbij 1 hidden is. Het is het hidden input veld dat nu rood wordt ipv het zichtbaar input veld.

**Gewenst gedrag**
Component zou rood moeten worden

**Comment by coemans** [comment]
Probleem is lokaal niet reproduceerbaar met onderstaande code. Doet het probleem zich nog voor op v3.2.0 of de #master branch?

```HTML
<vl-datepicker id="error-custom-format-datepicker" data-vl-format="d/m/Y" data-vl-error></vl-datepicker>
```

<img width="2560" alt="error" src="https://user-images.githubusercontent.com/11139249/96236792-c2a77000-0f9c-11eb-9b4e-4fb467fe330e.png">

**Comment by SBylemans** [comment]
@coemans Dit probleem doet zich nog voor.

**Comment by coemans** [comment]
@SBylemans is het mogelijk om de te volgen stappen toe te voegen aan dit issue zodat ik het probleem in isolatie kan reproduceren?

**Comment by SBylemans** [comment]
@coemans je moet gebruik maken van visual-format he:

`<vl-datepicker id="error-custom-format-datepicker" data-vl-format="d/m/Y" data-vl-visual-format='Y-m-d' data-vl-error></vl-datepicker>`

**Comment by coemans** [comment]
Dan kan ik het probleem ook niet reproduceren:

``` HTML
<vl-datepicker id="error-custom-format-datepicker" data-vl-visual-format="l d M Y" data-vl-error></vl-datepicker>
```

<img width="2560" alt="error-visual-format" src="https://user-images.githubusercontent.com/11139249/103345433-ad1cef00-4a91-11eb-899b-1265684eb783.png">

**Comment by SBylemans** [comment]
@coemans programmatisch zetten van data-vl-error in combinatie met data-visual-format werkt niet, ik heb een aparte branch met de issue aangemaakt (UIG-891)

**Comment by coemans** [comment]
@SBylemans dat probleem is inderdaad reproduceerbaar en werd opgelost in #148.
